# Site Info
remote_theme:       heiswayi/the-plain
title:              "random thoughts"
description:        "Don't count the days.Make the days count."
google_verify:       # Put your Google Verification here
google_analytics:   UA-111993556-1 # Put your Google Analytics code

# Author Info
author_name:        "Lampros Mousselimis" # Your name here
author_email:       lampros.mousselimis@gmail.com # Your email here
author_gravatar:    ebfa52e6ebf692911c0ba33b26514e53 # Your Gravatar md5 hash here for logo
twitter_username:   lmousselimis # Your Twitter username here
github_username:    lamprosmousselimis # Your GitHub username here

# Site Settings
url:                https://lamprosmousselimis.github.io # main url
baseurl:            /the-plain/ # for gh-pages
permalink:          /notes/:title # Post permalink
timezone:           Europe/Athens # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
input:              GFM
sass:
style:              :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
